### ISSUE TITLE
Program name

### ISSUE THREAD

**Issue by rwbc** [stockfishdeveloper/C---Bitboard-Chess-Engine#12]
Would you mind to rename the program to something less generic? 'Chess' makes it hard to differentiate it from other entities in computerchess archives. eg, the computerchesswiki and the XB/UCI chronology.
(http://computer-chess.org/doku.php?id=computer_chess:wiki:lists:chess_engine_list)
(http://rwbc-chess.de/chronology.htm)

**Comment by stockfishdeveloper** [comment]
Wow...
You're the first one to show interest in my project....
Thanks!

Well, I never really put much thought into a name--I just wanted to get it written and think of one later :)

Are you interested in helping me develop the engine?
