### ISSUE TITLE
How can I help and take part in your project?

### ISSUE THREAD

**Issue by DmitryAleksandrovich** [stockfishdeveloper/C---Bitboard-Chess-Engine#2]
Hello! I'd like to join your project.
A little about yourself: I'm junior C++ developer, and I don't have commercial development experience. If you have tasks (junior), I'm  happy to help project. Sorry with my not very confident English:)

**Comment by stockfishdeveloper** [comment]
Thank you very much for your interest in my C++ engine. Your help is greatly appreciated. Do you have any experience in making chess engines in the past? If so, you could potentially be a great help to me. If you are interested in becoming my "partner", you will have to be able to compile the project. naturally there are a few nuances to compiling it and i suggest that you try. If you get stuck, just ask me for help. By the way, my name is David.

Thank you and have a great time programming!
